### ISSUE TITLE
Kibana sometimes show up an error

### ISSUE THREAD

**Issue by alberttwong** [openshift-labs/starter-guides#18]
Did a roadshow and this happens to some of the students.   Not sure why.

**Comment by thoraxe** [comment]
What error?

**Comment by alberttwong** [comment]
I need to take a screenshot but when you click on the kibana link, kibana loads up with an error.  You have to click on reload and then the kibana page loads up correctly.

**Comment by gregswift** [comment]
When you get back to it is it the 'system:unauthorized' error?

**Comment by jorgemoralespou** [comment]
Not relevant anymore
