### ISSUE TITLE
Module-2 - Installing the *oc* client tool 

### ISSUE THREAD

**Issue by kmurudi** [openshift-labs/starter-guides#50]
The command -
$ export PATH=$PATH:~/OpenShift
does append the path to the end, but when I tried this lab, I had issues getting the correct version of 'oc'.
We can add these steps -
i) user first checks "$ which oc"
ii) moves the package downloaded for oc client tools from previous step to present working directory
using $ mv {oc-tool-package-extracted_name}/oc .
iii) check the new path again "$which oc"
and then check the version iv) "$oc version"

If error still persists - "$./oc version"

In the same section -- last part - displaying output of 'oc version' - \n character is displayed - which should have been a new line

**Comment by jorgemoralespou** [comment]
Not relevant anymore
