### ISSUE TITLE
Adjust project names in demos based on the use-cases deployed

### ISSUE THREAD

**Issue by siamaksade** [openshift-labs/starter-guides#53]
The project names are currently called CoolStore PROD and CI/CD regardless of the demo deployed uses CI/CD or not. The names should be adjusted to reflect the use-cases

**Comment by siamaksade** [comment]
Related to https://github.com/jbossdemocentral/coolstore-microservice/issues/73

**Comment by jorgemoralespou** [comment]
Not relevant anymore
